// ═══════════════════════════════════════════════════════════════
// Mock Data for Demo Modes — صالون وسبا العرابي بيوتي
// ═══════════════════════════════════════════════════════════════

export const DEMO_SALON_INFO = {
  name: 'صالون وسبا العرابي بيوتي',
  branch: 'الفرع الرئيسي - المهندسين',
  phone: '01023456789',
  address: 'شارع جامعة الدول العربية، المهندسين، الجيزة',
  taxNumber: 'TR-8492048-EG',
  currency: 'ج.م',
  rating: 4.9,
  reviewsCount: 348,
}

// 👑 بيانات الأونر (صاحبة الصالون)
export const DEMO_OWNER = {
  name: 'أ. نرمين العرابي',
  role: 'صاحبة الصالون والمدير العام',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
  stats: {
    todayRevenue: 24850,
    yesterdayRevenue: 19400,
    monthRevenue: 342500,
    targetMonth: 400000,
    activeAppointments: 18,
    completedToday: 26,
    activeStaff: 9,
    buffetRevenueToday: 2350,
    tipsCollectedToday: 1850,
    netProfitToday: 14200,
  },
  revenueChart: [
    { day: 'السبت', revenue: 21500, services: 32, buffet: 1800 },
    { day: 'الأحد', revenue: 18200, services: 28, buffet: 1400 },
    { day: 'الإثنين', revenue: 19800, services: 30, buffet: 1650 },
    { day: 'الثلاثاء', revenue: 22400, services: 35, buffet: 2100 },
    { day: 'الأربعاء', revenue: 20100, services: 29, buffet: 1950 },
    { day: 'الخميس', revenue: 28900, services: 44, buffet: 2900 },
    { day: 'الجمعة', revenue: 31200, services: 48, buffet: 3200 },
  ],
}

// ✂️ بيانات الكوافيرات وخبراء التجميل
export const DEMO_STYLISTS = [
  {
    id: 'st-1',
    name: 'مروة الجوهري',
    title: 'سينيور مصففة شعر وميكب آرتيست',
    specialty: 'قص وصبغات ومعالجات بروتين',
    avatar: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&q=80&w=300',
    phone: '01129384756',
    rating: 4.9,
    reviewsCount: 142,
    todayServicesCount: 6,
    commissionRate: 15, // 15%
    todayEarnings: 780,
    todayTips: 320,
    monthEarnings: 14250,
    isAvailable: true,
    currentStatus: 'في جلسة عمل (صالون شعر)',
  },
  {
    id: 'st-2',
    name: 'سارة عبد المنعم',
    title: 'أخصائية عناية بالبشرة وهيدرافيشل',
    specialty: 'تنظيف بشرة ومساج علاجي',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300',
    phone: '01098765432',
    rating: 4.8,
    reviewsCount: 98,
    todayServicesCount: 5,
    commissionRate: 15,
    todayEarnings: 620,
    todayTips: 250,
    monthEarnings: 11800,
    isAvailable: true,
    currentStatus: 'متاحة للحجز',
  },
  {
    id: 'st-3',
    name: 'نانسي يوسف',
    title: 'خبيرة تركيب أظافر وباديكير إسباني',
    specialty: 'أكريليك وجيل بولش وتصميم أظافر',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    phone: '01234567890',
    rating: 5.0,
    reviewsCount: 165,
    todayServicesCount: 7,
    commissionRate: 18,
    todayEarnings: 890,
    todayTips: 410,
    monthEarnings: 16400,
    isAvailable: false,
    currentStatus: 'في استراحة قصيرة (15 دقيقة)',
  },
  {
    id: 'st-4',
    name: 'دينا خليل',
    title: 'خبيرة ميك اب وتجهيز عرايس',
    specialty: 'ميكب سواريه وعرائس وكونتورينج',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    phone: '01555123456',
    rating: 4.9,
    reviewsCount: 112,
    todayServicesCount: 4,
    commissionRate: 20,
    todayEarnings: 950,
    todayTips: 500,
    monthEarnings: 18200,
    isAvailable: true,
    currentStatus: 'تجهيز قاعة العروسة',
  },
]

// 📅 مواعيد اليوم الخاصة بالكوافيرة مروة الجوهري (لنسخة الكوافيرة)
export const DEMO_STYLIST_APPOINTMENTS = [
  {
    id: 'apt-101',
    clientName: 'سيدة ياسمين صبري',
    clientPhone: '01011223344',
    time: '11:00 ص',
    service: 'بروتين علاجي نانو فيلر + قص أطراف',
    duration: '120 دقيقة',
    price: 1800,
    commission: 270,
    status: 'completed', // completed, in_progress, upcoming, cancelled
    statusText: 'تم الانتهاء بنجاح',
    notes: 'الشعر مصبوغ حديثاً يرجى استعمال حرارة متوسطة',
  },
  {
    id: 'apt-102',
    clientName: 'د. فريدة الشناوي',
    clientPhone: '01144556677',
    time: '01:30 م',
    service: 'صبغة اومبري لايت + سيشوار وبيبي ليس',
    duration: '90 دقيقة',
    price: 1250,
    commission: 187.5,
    status: 'in_progress',
    statusText: 'قيد التنفيذ الآن ⏳',
    notes: 'العميلة تفضل لون أشقر رمادي متوسط',
  },
  {
    id: 'apt-103',
    clientName: 'أ. ريم المحمودي',
    clientPhone: '01288990011',
    time: '03:30 م',
    service: 'قص شعر ليرز + ترميم بوتوكس كافيار',
    duration: '60 دقيقة',
    price: 850,
    commission: 127.5,
    status: 'upcoming',
    statusText: 'الموعد القادم',
    notes: 'حجز مؤكد مسبقاً عبر التطبيق',
  },
  {
    id: 'apt-104',
    clientName: 'أ. هناء زهران',
    clientPhone: '01077889900',
    time: '05:00 م',
    service: 'تسريحة ويفي سهرة + علاج سبليت إند',
    duration: '60 دقيقة',
    price: 700,
    commission: 105,
    status: 'upcoming',
    statusText: 'قادم',
    notes: 'عندها مناسبة الساعة 7 مساءً',
  },
]

// 💇‍♀️ قائمة الخدمات الكاملة في الصالون (للكاشير والعميلات)
export const DEMO_SERVICES = [
  {
    id: 'srv-1',
    category: 'شعر وتصفيف',
    name: 'قص شعر وتصفيف كلاسيكي / ليرز',
    price: 250,
    duration: '45 دقيقة',
    image: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&q=80&w=400',
    popular: true,
  },
  {
    id: 'srv-2',
    category: 'شعر وتصفيف',
    name: 'سيشوار ملكي + بيبي ليس سيراميك',
    price: 200,
    duration: '35 دقيقة',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=400',
    popular: true,
  },
  {
    id: 'srv-3',
    category: 'صبغات ومعالجات',
    name: 'صبغة كاملة لوريال بروفيشنال مع رينساج',
    price: 950,
    duration: '90 دقيقة',
    image: 'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&q=80&w=400',
    popular: true,
  },
  {
    id: 'srv-4',
    category: 'صبغات ومعالجات',
    name: 'معالج بروتين نانو كولاجين برازيلي أصلي',
    price: 1800,
    duration: '150 دقيقة',
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=400',
    popular: true,
  },
  {
    id: 'srv-5',
    category: 'عناية بالبشرة',
    name: 'جلسة هيدرافيشل ملكي عميق 9 مراحل',
    price: 650,
    duration: '60 دقيقة',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    popular: true,
  },
  {
    id: 'srv-6',
    category: 'عناية بالبشرة',
    name: 'تنظيف بشرة كلاسيكي + ماسك نضارة الذهب',
    price: 400,
    duration: '45 دقيقة',
    image: 'https://images.unsplash.com/photo-1512290900672-1f5be669e25d?auto=format&fit=crop&q=80&w=400',
    popular: false,
  },
  {
    id: 'srv-7',
    category: 'أظافر وباديكير',
    name: 'باديكير ومانيكير سبا بالشموع العطرية',
    price: 350,
    duration: '50 دقيقة',
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&q=80&w=400',
    popular: true,
  },
  {
    id: 'srv-8',
    category: 'أظافر وباديكير',
    name: 'تركيب أظافر أكريليك مع ديزاين جيل بولش',
    price: 550,
    duration: '70 دقيقة',
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&q=80&w=400',
    popular: false,
  },
  {
    id: 'srv-9',
    category: 'مكياج ومناسبات',
    name: 'مكياج سواريه احترافي كامل مع رموش 3D',
    price: 750,
    duration: '60 دقيقة',
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80&w=400',
    popular: true,
  },
  {
    id: 'srv-10',
    category: 'حمام مغربي وسبا',
    name: 'حمام مغربي ملكي بالأعشاب والطمي المغربي',
    price: 850,
    duration: '80 دقيقة',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=400',
    popular: true,
  },
]

// 🛍️ المنتجات والمستحضرات بالمخزن
export const DEMO_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'شامبو لوريال إكسبرت الخالي من السلفات 500 مل',
    category: 'عناية بالشعر',
    costPrice: 280,
    sellPrice: 420,
    stock: 24,
    minStock: 5,
    salesCount: 68,
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'prod-2',
    name: 'سيروم الأرجان المغربي المعالج للتقصف 100 مل',
    category: 'عناية بالشعر',
    costPrice: 210,
    sellPrice: 350,
    stock: 18,
    minStock: 4,
    salesCount: 84,
    image: 'https://images.unsplash.com/photo-1608248597359-5975d0458dfa?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'prod-3',
    name: 'ماسك الكولاجين والذهب لترطيب البشرة',
    category: 'عناية بالبشرة',
    costPrice: 150,
    sellPrice: 260,
    stock: 3, // Low stock!
    minStock: 5,
    salesCount: 42,
    image: 'https://images.unsplash.com/photo-1567928815116-f6d90a6e0d37?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'prod-4',
    name: 'مجموعة زيت شجرة الشاي لتنقية فروة الرأس',
    category: 'عناية بالشعر',
    costPrice: 320,
    sellPrice: 490,
    stock: 12,
    minStock: 3,
    salesCount: 31,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&q=80&w=300',
  },
]

// ☕ بوفيه المشروبات والضيافة
export const DEMO_BUFFET_ITEMS = [
  { id: 'buf-1', name: 'قهوة تركي مخصوص بالحبهان', price: 35, category: 'ساخن', icon: '☕' },
  { id: 'buf-2', name: 'كابتشينو إيطالي برغوة الحليب', price: 50, category: 'ساخن', icon: '🥛' },
  { id: 'buf-3', name: 'لاتيه كراميل / فانيليا', price: 55, category: 'ساخن', icon: '☕' },
  { id: 'buf-4', name: 'موهيتو فراولة وبلو بيري منعش', price: 60, category: 'بارد', icon: '🍹' },
  { id: 'buf-5', name: 'عصير برتقال فريش طبيعي', price: 45, category: 'بارد', icon: '🍊' },
  { id: 'buf-6', name: 'مياه معدنية مثلجة', price: 15, category: 'مشروبات', icon: '💧' },
]

// 🏷️ عروض الماركتينج والكوبونات
export const DEMO_MARKETING_OFFERS = [
  {
    id: 'off-1',
    title: 'باقة العروسة الملكية الشاملة 👰',
    badge: 'الأكثر طلباً',
    originalPrice: 4500,
    offerPrice: 3200,
    discountPercent: 29,
    description: 'تشمل ميكب كامل + باديكير ومانيكير سبا + حمام مغربي ملكي + سيشوار وترميم للشعر + جلسة نضارة',
    endDate: '2026-11-30',
    claimedCount: 42,
    active: true,
  },
  {
    id: 'off-2',
    title: 'عرض هيدرافيشل + سيشوار وبيبي ليس هدية 💆‍♀️',
    badge: 'عرض الأسبوع',
    originalPrice: 850,
    offerPrice: 599,
    discountPercent: 30,
    description: 'تنظيف عميق 9 مراحل بأحدث جهاز هيدرافيشل مع تصفيف الشعر مجاناً',
    endDate: '2026-10-31',
    claimedCount: 88,
    active: true,
  },
  {
    id: 'off-3',
    title: 'خصم البروتين البرازيلي للشعر الطويل ✨',
    badge: 'خصم خاص',
    originalPrice: 2200,
    offerPrice: 1599,
    discountPercent: 27,
    description: 'فرد وترميم حراري بأجود الخامات البرازيلية مع قص الأطراف وحمام زيت مجاني',
    endDate: '2026-11-15',
    claimedCount: 56,
    active: true,
  },
]

export const DEMO_COUPONS = [
  { code: 'BEAUTY20', discount: 20, type: 'percent', minSpend: 500, uses: 124, active: true },
  { code: 'QUEEN100', discount: 100, type: 'fixed', minSpend: 800, uses: 65, active: true },
  { code: 'WELCOME10', discount: 10, type: 'percent', minSpend: 200, uses: 310, active: true },
]

// ⭐ آراء العميلات والتقييمات
export const DEMO_REVIEWS = [
  {
    id: 'rev-1',
    clientName: 'مريم الصاوي',
    stylistName: 'مروة الجوهري',
    rating: 5,
    date: 'منذ ساعتين',
    comment: 'مروة مبدعة بجد! عملتلي بروتين للشعر والنتيجة انسيابية وناعمة جداً ومعاملة ستاف المكان راقية ومحترمة فوق الوصف.',
    service: 'بروتين نانو فيلر',
    verified: true,
    published: true,
  },
  {
    id: 'rev-2',
    clientName: 'نوران الشاذلي',
    stylistName: 'سارة عبد المنعم',
    rating: 5,
    date: 'أمس',
    comment: 'جلسة الهيدرافيشل نضفت بشرتي بجد والفرق واضح من أول دقيقة.. البوفيه والموهيتو يجنن شكراً ليكم.',
    service: 'هيدرافيشل ملكي',
    verified: true,
    published: true,
  },
  {
    id: 'rev-3',
    clientName: 'خلود العوضي',
    stylistName: 'نانسي يوسف',
    rating: 5,
    date: 'منذ يومين',
    comment: 'الأظافر شغلها دقيق جداً ونانسي فنانة وسريعة.. الصالون منظم ونظيف جداً وأكيد هرجع تاني.',
    service: 'أظافر أكريليك',
    verified: true,
    published: true,
  },
  {
    id: 'rev-4',
    clientName: 'رانيا منصور',
    stylistName: 'دينا خليل',
    rating: 4,
    date: 'منذ 3 أيام',
    comment: 'الميكب كان ثابت وجميل والكل سألني عليه في الخطوبة، بس كان فيه تأخير بسيط 10 دقايق في الموعد.',
    service: 'ميكب سواريه',
    verified: true,
    published: true,
  },
]

// 🧾 فواتير الكاشير الأخيرة (للتجربة)
export const DEMO_INVOICES = [
  {
    id: 'INV-2026-084',
    clientName: 'أ. داليا الشريف',
    clientPhone: '01019283746',
    date: '2026-10-07 14:15',
    items: [
      { name: 'صبغة كاملة لوريال', price: 950, qty: 1, stylist: 'مروة الجوهري' },
      { name: 'سيشوار ملكي', price: 200, qty: 1, stylist: 'مروة الجوهري' },
      { name: 'موهيتو فراولة', price: 60, qty: 1, isBuffet: true },
    ],
    subtotal: 1210,
    discount: 100,
    tax: 0,
    total: 1110,
    paymentMethod: 'فيزا / بطاقة بنكية',
    cashierName: 'أحمد سعيد',
  },
  {
    id: 'INV-2026-083',
    clientName: 'مدام هالة فهمي',
    clientPhone: '01223344556',
    date: '2026-10-07 13:40',
    items: [
      { name: 'باديكير ومانيكير سبا', price: 350, qty: 1, stylist: 'نانسي يوسف' },
      { name: 'شامبو لوريال إكسبرت', price: 420, qty: 1, isProduct: true },
      { name: 'قهوة تركي', price: 35, qty: 1, isBuffet: true },
    ],
    subtotal: 805,
    discount: 0,
    tax: 0,
    total: 805,
    paymentMethod: 'نقدي (كاش)',
    cashierName: 'أحمد سعيد',
  },
]
